#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Mar 03 09:02:28 ICT 2023
maven-metadata-terracotta-releases.xml.error=
maven-metadata-terracotta-snapshots.xml.error=Could not transfer metadata com.globits\:core-v2-api\:1.0.0-SNAPSHOT/maven-metadata.xml from/to terracotta-snapshots (http\://www.terracotta.org/download/reflector/snapshots)\: Authorization failed for http\://www.terracotta.org/download/reflector/snapshots/com/globits/core-v2-api/1.0.0-SNAPSHOT/maven-metadata.xml 403 Forbidden
maven-metadata-terracotta-releases.xml.lastUpdated=1654676376776
maven-metadata-terracotta-snapshots.xml/@default-terracotta-snapshots-http\://www.terracotta.org/download/reflector/snapshots/.lastUpdated=1654676376760
maven-metadata-maven-snapshots.xml.lastUpdated=1658457836207
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata com.globits\:core-v2-api\:1.0.0-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: transfer failed for http\://0.0.0.0/com/globits/core-v2-api/1.0.0-SNAPSHOT/maven-metadata.xml
maven-metadata-central.xml.lastUpdated=1677808944612
maven-metadata-central.xml.error=
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1677808948844
