#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Mar 03 09:02:28 ICT 2023
maven-metadata-maven-snapshots.xml.lastUpdated=1658457836394
maven-metadata-maven-default-http-blocker.xml.error=Could not transfer metadata com.globits\:core-v2\:1.0.0-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http\://0.0.0.0/)\: transfer failed for http\://0.0.0.0/com/globits/core-v2/1.0.0-SNAPSHOT/maven-metadata.xml
maven-metadata-central.xml.lastUpdated=1659346579238
maven-metadata-central.xml.error=
maven-metadata-maven-default-http-blocker.xml/@default-maven-default-http-blocker-http\://0.0.0.0/.lastUpdated=1677808948843
